version: '2'
services:
  workspace:
    build:
      context: ./services/workspace
      dockerfile: Dockerfile
    volumes_from:
      - php
    tty: true
  web:
    image: nginx:1.11.6
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ~/dev/docker-php-env/services/nginx/config:/etc/nginx/conf.d
  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    volumes:
      - ~/dev/docker-php-env/www:/web/www
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "3d_travel_platform"
      MYSQL_USER: "yafei"
      MYSQL_PASSWORD: "520123"
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis:3.2.5
    ports:
      - "6379:6379"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: "root"
volumes:
  db:
    driver: local
