FROM nginx:1.11.6
MAINTAINER ouyafei <321177122@qq.com>
#WORKDIR /web/www

#切换阿里云的 debian 8 jessie 源
#RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list
#RUN apt-get update

ADD nginx.conf /etc/nginx/
